### ISSUE TITLE
何故か「あざま」でログインされている

### ISSUE THREAD

**Issue by AnaTofuZ** [Azama-K/gingdagoz#12]
バグ報告です。

何故かトップページを開くと、会員登録/ログイン等していないですが「あざまでログインしています」と表示されてしまいます。

![Screen Shot 2020-11-13 at 14 04 34](https://user-images.githubusercontent.com/13062611/99030968-4151f600-25b9-11eb-8cbc-6f3859b61441.jpg)

なんとなくこのあたりが怪しい気がしますが、詳細はわかりません...!!
https://github.com/Azama-K/gingdagoz/blob/ada59c17f3bb6582d12a3a83a38550814855ae65/app/views/homes/index.html.erb#L9

**Comment by Azama-K** [comment]
まだログイン関係がうまくいってないのでとりあえずこのような形にしてました。

**Comment by himajin315** [comment]
ログイン関係は devise を使ったら、比較的早くに実装できるかと思いますよ 🤔

**Comment by Capi53** [comment]
直しました〜
